//! T17-04 acceptance test: "old spool versions import" (spec 11 §4 `[FIXED
//! concern]`: "a daemon MUST be able to import all spool `format_version`s ≤
//! its own").
//!
//! `local_rag_core::spool::FORMAT_VERSION` has been `1` since it was
//! introduced and has never been bumped, so there is no real *older* version
//! to import today — the behavioral gap this card names does not exist yet.
//! What this test establishes instead is the **pattern** and the **anchor**:
//! a real, byte-frozen format-version-1 segment, captured once by running
//! today's encoder and pasted here as a literal, decoded by whatever decoder
//! ships in the future. This must **not** be regenerated by calling the live
//! encoder inside the test — the day `FORMAT_VERSION` bumps to 2, the live
//! encoder itself starts emitting v2, and a live-generated "v1 fixture" would
//! silently follow it, defeating the entire point. When that bump happens,
//! add a new `V2_SEGMENT_BYTES` fixture alongside this one (captured the same
//! way, once, under the `FORMAT_VERSION == 2` encoder) rather than editing
//! this one.

use local_rag_core::identity::{UuidSource, uuidv7_from};
use local_rag_core::paths::StoreLayout;
use local_rag_store::{RequestRoot, StateDb, import_session_tail};
use local_rag_test_support::TempHome;

/// Captured once via `encode_segment_header()` + `encode_frame(&FramePayload
/// { format_version: 1, .. })` while `local_rag_core::spool::FORMAT_VERSION
/// == 1` (see this module's doc comment — frozen forever, never regenerated).
/// Header (16 bytes: `LRSP`, version 1, flags 0, reserved) followed by one
/// frame (`len` u32 LE ‖ `crc32c` u32 LE ‖ canonical-JSON `FramePayload`) for
/// a best-effort-dedup `Stop` event on session `v1-fixture-session`, one path
/// (`src/lib.rs`), a redacted payload/short-excerpt pair, and
/// `redaction_version: 1`.
#[rustfmt::skip]
const V1_SEGMENT_BYTES: &[u8] = &[
    76, 82, 83, 80, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    155, 1, 0, 0, 179, 13, 106, 3, 123, 34, 102, 111, 114, 109, 97, 116,
    95, 118, 101, 114, 115, 105, 111, 110, 34, 58, 49, 44, 34, 115, 111, 117,
    114, 99, 101, 95, 101, 118, 101, 110, 116, 95, 105, 100, 34, 58, 34, 115,
    116, 58, 118, 49, 45, 102, 105, 120, 116, 117, 114, 101, 45, 115, 101, 115,
    115, 105, 111, 110, 58, 49, 34, 44, 34, 100, 101, 100, 117, 112, 95, 107,
    101, 121, 34, 58, 110, 117, 108, 108, 44, 34, 101, 118, 101, 110, 116, 95,
    116, 121, 112, 101, 34, 58, 34, 83, 116, 111, 112, 34, 44, 34, 99, 97,
    112, 116, 117, 114, 101, 100, 95, 97, 116, 34, 58, 49, 55, 48, 48, 48,
    48, 48, 48, 48, 48, 48, 48, 48, 44, 34, 115, 101, 115, 115, 105, 111,
    110, 95, 105, 100, 34, 58, 34, 118, 49, 45, 102, 105, 120, 116, 117, 114,
    101, 45, 115, 101, 115, 115, 105, 111, 110, 34, 44, 34, 97, 103, 101, 110,
    116, 95, 105, 100, 34, 58, 110, 117, 108, 108, 44, 34, 116, 117, 114, 110,
    95, 105, 100, 34, 58, 110, 117, 108, 108, 44, 34, 98, 97, 116, 99, 104,
    95, 105, 100, 34, 58, 110, 117, 108, 108, 44, 34, 119, 111, 114, 107, 116,
    114, 101, 101, 95, 114, 111, 111, 116, 34, 58, 110, 117, 108, 108, 44, 34,
    99, 111, 109, 109, 105, 116, 34, 58, 110, 117, 108, 108, 44, 34, 101, 118,
    105, 100, 101, 110, 99, 101, 95, 107, 105, 110, 100, 34, 58, 34, 109, 111,
    100, 101, 108, 95, 99, 108, 97, 105, 109, 34, 44, 34, 116, 114, 117, 115,
    116, 34, 58, 34, 108, 111, 119, 34, 44, 34, 112, 97, 116, 104, 115, 34,
    58, 91, 34, 115, 114, 99, 47, 108, 105, 98, 46, 114, 115, 34, 93, 44,
    34, 114, 101, 100, 97, 99, 116, 105, 111, 110, 95, 118, 101, 114, 115, 105,
    111, 110, 34, 58, 49, 44, 34, 112, 97, 121, 108, 111, 97, 100, 34, 58,
    34, 92, 34, 97, 32, 114, 101, 100, 97, 99, 116, 101, 100, 32, 99, 108,
    97, 105, 109, 92, 34, 34, 44, 34, 115, 104, 111, 114, 116, 95, 101, 118,
    105, 100, 101, 110, 99, 101, 95, 101, 120, 99, 101, 114, 112, 116, 34, 58,
    34, 97, 32, 114, 101, 100, 97, 99, 116, 101, 100, 32, 99, 108, 97, 105,
    109, 34, 125,
];

fn open_state() -> (TempHome, StoreLayout, StateDb) {
    let home = TempHome::new().expect("temp home");
    let layout = StoreLayout::new(home.join("local-rag"));
    layout.ensure().expect("ensure store tree");
    let db = StateDb::open(layout.state_db()).expect("open state.sqlite");
    (home, layout, db)
}

struct FixedUuid;
impl UuidSource for FixedUuid {
    fn next_uuid(&self) -> local_rag_core::identity::Uuid {
        uuidv7_from(1_700_000_000_000, [0xCD; 10])
    }
}

/// A real, frozen format-version-1 spool segment still imports cleanly under
/// today's (still format-version-1) decoder — the anchor this module's doc
/// comment describes.
#[tokio::test]
async fn a_real_v1_spool_segment_still_imports_at_head() {
    let (_home, layout, db) = open_state();
    let session_dir = layout.spool_session("v1-fixture-session");
    std::fs::create_dir_all(&session_dir).expect("session dir");
    std::fs::write(session_dir.join("000001.seg"), V1_SEGMENT_BYTES).expect("write v1 fixture");

    let outcome = import_session_tail(
        &db,
        &layout,
        "v1-fixture-session",
        &RequestRoot::default(),
        &FixedUuid,
        1_700_000_000_000,
        72,
    )
    .await
    .expect("a real v1 segment imports without error");

    assert!(
        outcome.stalled_on.is_none(),
        "a real v1 segment must not stall: {:?}",
        outcome.stalled_on
    );
    assert_eq!(outcome.report.imported, 1, "the one frame is imported");
    assert_eq!(outcome.report.exact_duplicates, 0);
    assert_eq!(outcome.report.window_duplicates, 0);
    assert!(outcome.report.saw_stop, "the frame's event_type is Stop");

    let read = db.open_read().expect("read conn");
    let (event_type, session_id, evidence_kind): (String, String, String) = read
        .query_row(
            "SELECT event_type, session_id, evidence_kind FROM observation_envelope \
             WHERE source_event_id = 'st:v1-fixture-session:1'",
            [],
            |r| Ok((r.get(0)?, r.get(1)?, r.get(2)?)),
        )
        .expect("the v1 fixture's envelope row is present");
    assert_eq!(event_type, "Stop");
    assert_eq!(session_id, "v1-fixture-session");
    assert_eq!(evidence_kind, "model_claim");
}
